#### **Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.arange(12, 24)

print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(12, 1)
print(a1)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [4]:
a2 = a.reshape(6, 2)
print(a2)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [5]:
a3 = a.reshape(3, 4)
print(a3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
a4 = a.reshape(4, 3)
print(a4)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [7]:
a5 = a.reshape(2, 6)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a1 = a.reshape(12, -1)
print(a1)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [9]:
a2 = a.reshape(6, -1)
print(a2)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [10]:
a3 = a.reshape(3, -1)
print(a3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [11]:
a4 = a.reshape(-1, 3)
print(a4)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [12]:
a5 = a.reshape(-1, 1)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? Нет.

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [13]:
a = np.random.randn(3, 4)
print(a)

[[ 0.39740138 -0.56736049  1.04616753 -0.35979265]
 [ 0.67670486 -0.25727918  1.00212945 -1.05520557]
 [-0.72621734  1.2429235  -2.0013575   0.32497887]]


In [14]:
a1 = a.flatten()
print(a1)

[ 0.39740138 -0.56736049  1.04616753 -0.35979265  0.67670486 -0.25727918
  1.00212945 -1.05520557 -0.72621734  1.2429235  -2.0013575   0.32497887]


In [15]:
a1.size == a.size

True

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [16]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [17]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [18]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Массивы не имеют разницы

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [19]:
x = 3 # число строк массива b
a = np.zeros(((x - 1), 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [20]:
b = np.ones((x, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
v = np.concatenate((a, b), axis = 0)
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [23]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [26]:
B = A.dot(At)
print(B, "size (B) =", B.size)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] size (B) = 16


In [27]:
d = np.linalg.det(B)
print(d)

0.0


 Вычислить обратную матрицу для матрицы B не возможно, т.к. ее определитель = 0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [28]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [29]:
c = np.arange(0, 16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [30]:
C = c.reshape((4, 4))
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
C.shape == B.shape

True

In [32]:
D = 10 * C + B
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [33]:
np.linalg.det(D)

-7.685903354004529e-25

In [34]:
rank_D = np.linalg.matrix_rank(D)
print("ранг D=", rank_D)

ранг D= 2


In [35]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [36]:
D_inv[(D_inv > 0)] = 1
D_inv[D_inv < 0] = 0
print(D_inv)

[[1. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [37]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14   2  32]
 [  4  50  86   7]
 [ 23   9  10 212]
 [ 12 122  14  15]]
