In [6]:
import numpy as np

### task1

In [7]:
a = np.array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### task2

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### task3

In [16]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [18]:
a_rez= a_centered_sp / (a.shape[0] - 1)
a_rez

2.0

### task4

In [19]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [21]:
a_rez = np.cov(a.T)[0, 1]
a_rez

2.0